Repository Team-ThreeGo/Algo-Backend, pull requests merged in 2025-09, with the labels that each got.

#9 [Feat] #2 - 기업별 정보 공유 조회 API 구현
  src/main/java/com/threego/algo/career/command/domain/aggregate/.gitkeep
  src/main/java/com/threego/algo/career/command/domain/aggregate/CareerInfoPost.java
  src/main/java/com/threego/algo/career/command/domain/aggregate/enums/Status.java
  src/main/java/com/threego/algo/career/query/controller/.gitkeep
  src/main/java/com/threego/algo/career/query/controller/AdminCareerQueryController.java
  src/main/java/com/threego/algo/career/query/controller/CareerQueryController.java
  src/main/java/com/threego/algo/career/query/dao/.gitkeep
  src/main/java/com/threego/algo/career/query/dao/CareerInfoMapper.java
  src/main/java/com/threego/algo/career/query/dto/.gitkeep
  src/main/java/com/threego/algo/career/query/dto/CommentResponseDto.java
  src/main/java/com/threego/algo/career/query/dto/PostDetailResponseDto.java
  src/main/java/com/threego/algo/career/query/dto/PostSummaryResponseDto.java
  src/main/java/com/threego/algo/career/query/service/.gitkeep
  src/main/java/com/threego/algo/career/query/service/CareerQueryService.java
  src/main/java/com/threego/algo/career/query/service/CareerQueryServiceImpl.java
  src/main/resources/com/threego/algo/career/query/dao/CareerInfoMapper.xml
Labels: 기업별 정보 공유

#6 [Feat] #4 study-recruit 조회 기능 구현
  src/main/java/com/threego/algo/study/query/controller/.gitkeep
  src/main/java/com/threego/algo/study/query/controller/AdminStudyPostQueryController.java
  src/main/java/com/threego/algo/study/query/controller/StudyPostQueryController.java
  src/main/java/com/threego/algo/study/query/dao/.gitkeep
  src/main/java/com/threego/algo/study/query/dao/StudyMemberMapper.java
  src/main/java/com/threego/algo/study/query/dao/StudyPostMapper.java
  src/main/java/com/threego/algo/study/query/dao/StudyRoadmapMapper.java
  src/main/java/com/threego/algo/study/query/dto/.gitkeep
  src/main/java/com/threego/algo/study/query/dto/StudyCommentDTO.java
  src/main/java/com/threego/algo/study/query/dto/StudyMemberDTO.java
  src/main/java/com/threego/algo/study/query/dto/StudyPostDTO.java
  src/main/java/com/threego/algo/study/query/dto/StudyPostDetailDTO.java
  src/main/java/com/threego/algo/study/query/dto/StudyPostSearchDTO.java
  src/main/java/com/threego/algo/study/query/dto/StudyRoadmapDTO.java
  src/main/java/com/threego/algo/study/query/dto/StudyRoadmapDetailDTO.java
  src/main/java/com/threego/algo/study/query/service/.gitkeep
  src/main/java/com/threego/algo/study/query/service/StudyMemberQueryService.java
  src/main/java/com/threego/algo/study/query/service/StudyMemberQueryServiceImpl.java
  src/main/java/com/threego/algo/study/query/service/StudyPostQueryService.java
  src/main/java/com/threego/algo/study/query/service/StudyPostQueryServiceImpl.java
  src/main/java/com/threego/algo/study/query/service/StudyRoadmapQueryService.java
  src/main/java/com/threego/algo/study/query/service/StudyRoadmapQueryServiceImpl.java
  src/main/java/com/threego/algo/studyrecruit/query/controller/.gitkeep
  src/main/java/com/threego/algo/studyrecruit/query/controller/AdminStudyRecruitPostQueryController.java
  src/main/java/com/threego/algo/studyrecruit/query/controller/StudyRecruitPostQueryController.java
  src/main/java/com/threego/algo/studyrecruit/query/dao/.gitkeep
  src/main/java/com/threego/algo/studyrecruit/query/dao/StudyRecruitCommentMapper.java
  src/main/java/com/threego/algo/studyrecruit/query/dao/StudyRecruitPostMapper.java
  src/main/java/com/threego/algo/studyrecruit/query/dto/.gitkeep
  src/main/java/com/threego/algo/studyrecruit/query/dto/StudyRecruitCommentDTO.java
  src/main/java/com/threego/algo/studyrecruit/query/dto/StudyRecruitDetailDTO.java
  src/main/java/com/threego/algo/studyrecruit/query/dto/StudyRecruitMemberDTO.java
  src/main/java/com/threego/algo/studyrecruit/query/dto/StudyRecruitPostDTO.java
  src/main/java/com/threego/algo/studyrecruit/query/dto/StudyRecruitSearchDTO.java
  src/main/java/com/threego/algo/studyrecruit/query/service/.gitkeep
  src/main/java/com/threego/algo/studyrecruit/query/service/StudyRecruitPostQueryService.java
  src/main/java/com/threego/algo/studyrecruit/query/service/StudyRecruitPostQueryServiceImpl.java
  src/main/resources/.gitkeep
  src/main/resources/com/threego/algo/study/query/dao/StudyMemberMapper.xml
  src/main/resources/com/threego/algo/study/query/dao/StudyPostMapper.xml
  src/main/resources/com/threego/algo/study/query/dao/StudyRoadmapMapper.xml
  src/main/resources/com/threego/algo/studyrecruit/query/dao/StudyRecruitCommentMapper.xml
  src/main/resources/com/threego/algo/studyrecruit/query/dao/StudyRecruitPostMapper.xml
Labels: 스터디

#18 [Feat] #8 - 인증 기능 구현
  build.gradle
  src/main/java/com/threego/algo/auth/command/application/controller/AuthController.java
  src/main/java/com/threego/algo/auth/command/application/controller/MailController.java
  src/main/java/com/threego/algo/auth/command/application/dto/RequestLoginDTO.java
  src/main/java/com/threego/algo/auth/command/application/dto/RequestRegistUserDTO.java
  src/main/java/com/threego/algo/auth/command/application/dto/ResponseRegistUserDTO.java
  src/main/java/com/threego/algo/auth/command/application/dto/UserDTO.java
  src/main/java/com/threego/algo/auth/command/application/service/AuthService.java
  src/main/java/com/threego/algo/auth/command/application/service/AuthServiceImpl.java
  src/main/java/com/threego/algo/auth/command/application/service/AuthenticationFilter.java
  src/main/java/com/threego/algo/auth/command/application/service/JwtAuthenticationProvider.java
  src/main/java/com/threego/algo/auth/command/application/service/MailService.java
  src/main/java/com/threego/algo/auth/command/application/service/MailServiceImpl.java
  src/main/java/com/threego/algo/auth/command/domain/aggregate/.gitkeep
  src/main/java/com/threego/algo/auth/command/domain/repository/.gitkeep
  src/main/java/com/threego/algo/auth/command/domain/service/.gitkeep
  src/main/java/com/threego/algo/auth/command/infrastructure/security/JwtFilter.java
  src/main/java/com/threego/algo/auth/command/infrastructure/security/JwtUtil.java
  src/main/java/com/threego/algo/auth/command/infrastructure/security/WebSecurity.java
  src/main/java/com/threego/algo/auth/command/infrastructure/service/.gitkeep
  src/main/java/com/threego/algo/config/AppConfig.java
  src/main/java/com/threego/algo/member/command/domain/aggregate/Member.java
  src/main/java/com/threego/algo/member/command/domain/repository/MemberRepository.java
  src/main/java/com/threego/algo/member/query/controller/AuthQueryController.java
  src/main/java/com/threego/algo/member/query/dao/AuthMapper.java
  src/main/java/com/threego/algo/member/query/dao/MemberMapper.java
  src/main/java/com/threego/algo/member/query/dto/LoginUserResponseDTO.java
  src/main/java/com/threego/algo/member/query/dto/MemberDetailResponseDTO.java
  src/main/java/com/threego/algo/member/query/service/AuthQueryService.java
  src/main/java/com/threego/algo/member/query/service/AuthQueryServiceImpl.java
  src/main/resources/com/threego/algo/member/query/dao/AuthMapper.xml
  src/main/resources/com/threego/algo/member/query/dao/MemberMapper.xml
Labels: 회원

#22 [feat] #16 - 회원 조회 기능 구현
  src/main/java/com/threego/algo/member/query/controller/AdminMemberQueryController.java
  src/main/java/com/threego/algo/member/query/controller/MemberQueryController.java
  src/main/java/com/threego/algo/member/query/dao/MemberMapper.java
  src/main/java/com/threego/algo/member/query/dto/.gitkeep
  src/main/java/com/threego/algo/member/query/dto/AdminMemberDetailResponseDTO.java
  src/main/java/com/threego/algo/member/query/service/AdminMemberQueryService.java
  src/main/java/com/threego/algo/member/query/service/AdminMemberQueryServiceImpl.java
  src/main/java/com/threego/algo/member/query/service/MemberQueryService.java
  src/main/java/com/threego/algo/member/query/service/MemberQueryServiceImpl.java
  src/main/resources/com/threego/algo/member/query/dao/MemberMapper.xml
Labels: 회원

#32 [Feat] #28 - S3를 통한 게시물에 이미지 넣기 기능 개발
  build.gradle
  src/main/java/com/threego/algo/algorithm/command/application/controller/AdminAlgoCommandController.java
  src/main/java/com/threego/algo/algorithm/command/application/dto/AlgoPostRequestDTO.java
  src/main/java/com/threego/algo/algorithm/command/application/service/AlgoCommandServiceImpl.java
  src/main/java/com/threego/algo/career/command/application/controller/CareerCommandController.java
  src/main/java/com/threego/algo/career/command/application/dto/CareerPostCreateRequest.java
  src/main/java/com/threego/algo/career/command/application/service/CareerCommandServiceImpl.java
  src/main/java/com/threego/algo/coding/command/application/controller/CodingPostCommandController.java
  src/main/java/com/threego/algo/coding/command/application/dto/CodingPostImageRequestDTO.java
  src/main/java/com/threego/algo/coding/command/application/dto/CodingPostRequestDTO.java
  src/main/java/com/threego/algo/coding/command/application/service/CodingPostCommandServiceImpl.java
  src/main/java/com/threego/algo/coding/command/domain/repository/CodingPostImageRepository.java
  src/main/java/com/threego/algo/common/service/S3Service.java
  src/main/java/com/threego/algo/study/command/application/controller/StudyPostCommandController.java
  src/main/java/com/threego/algo/study/command/application/dto/create/StudyPostCreateResponseDTO.java
  src/main/java/com/threego/algo/study/command/application/dto/create/StudyPostRequestDTO.java
  src/main/java/com/threego/algo/study/command/application/service/StudyPostService.java
  src/main/java/com/threego/algo/study/command/application/service/StudyPostServiceImpl.java
  src/main/java/com/threego/algo/study/command/domain/aggregate/StudyPost.java
  src/main/java/com/threego/algo/study/command/domain/aggregate/StudyPostImage.java
Labels: 알고리즘 학습, 스터디, 기업별 정보 공유, 코딩 풀이

#33 [Feat] #26 - 추천 관련 API 구현
  src/main/java/com/threego/algo/algorithm/command/application/controller/AdminAlgoCommandController.java
  src/main/java/com/threego/algo/algorithm/command/application/controller/AlgoCommandController.java
  src/main/java/com/threego/algo/algorithm/command/application/service/AlgoCommandService.java
  src/main/java/com/threego/algo/algorithm/command/application/service/AlgoCommandServiceImpl.java
  src/main/java/com/threego/algo/algorithm/command/domain/aggregate/AlgoPost.java
  src/main/java/com/threego/algo/algorithm/query/controller/AdminAlgoQueryController.java
  src/main/java/com/threego/algo/algorithm/query/controller/AlgoQueryController.java
  src/main/java/com/threego/algo/algorithm/query/service/AlgoQueryServiceImpl.java
  src/main/java/com/threego/algo/career/command/application/controller/CareerCommandController.java
  src/main/java/com/threego/algo/career/command/application/service/CareerCommandService.java
  src/main/java/com/threego/algo/career/command/application/service/CareerCommandServiceImpl.java
  src/main/java/com/threego/algo/career/command/domain/aggregate/CareerInfoPost.java
  src/main/java/com/threego/algo/coding/command/application/controller/CodingPostCommandController.java
  src/main/java/com/threego/algo/coding/command/application/service/CodingPostCommandService.java
  src/main/java/com/threego/algo/coding/command/application/service/CodingPostCommandServiceImpl.java
  src/main/java/com/threego/algo/coding/command/domain/aggregate/CodingPost.java
  src/main/java/com/threego/algo/likes/command/application/service/LikesCommandService.java
  src/main/java/com/threego/algo/likes/command/application/service/LikesCommandServiceImpl.java
  src/main/java/com/threego/algo/likes/command/domain/aggregate/.gitkeep
  src/main/java/com/threego/algo/likes/command/domain/aggregate/Likes.java
  src/main/java/com/threego/algo/likes/command/domain/aggregate/enums/Type.java
  src/main/java/com/threego/algo/likes/command/domain/repository/.gitkeep
  src/main/java/com/threego/algo/likes/command/domain/repository/LikesCommandRepository.java
  src/main/java/com/threego/algo/likes/query/dao/.gitkeep
  src/main/java/com/threego/algo/likes/query/dao/LikesMapper.java
  src/main/java/com/threego/algo/likes/query/service/.gitkeep
  src/main/java/com/threego/algo/likes/query/service/LikesQueryService.java
  src/main/java/com/threego/algo/likes/query/service/LikesQueryServiceImpl.java
  src/main/java/com/threego/algo/member/command/domain/aggregate/Member.java
  src/main/resources/com/threego/algo/likes/query/dao/LikesMapper.xml
Labels: 추천

#39 [Fix] #38 - Merge 충돌로 인한 잘못된 Repository 호출 수정
  src/main/java/com/threego/algo/algorithm/command/application/service/AlgoCommandServiceImpl.java
Labels: Hotfix, 알고리즘 학습

#43 feat: #34 - 코딩관련 ai 추가 및 컬럼명수정,테스트케이스코드 작성
  src/main/java/com/threego/algo/coding/command/application/dto/CodingPostRequestDTO.java
  src/main/java/com/threego/algo/coding/command/application/dto/CodingProblemRequestDTO.java
  src/main/java/com/threego/algo/coding/command/application/service/AdminCodingPostCommandServiceImpl.java
  src/main/java/com/threego/algo/coding/command/application/service/CodingPostCommandServiceImpl.java
  src/main/java/com/threego/algo/coding/command/domain/aggregate/CodingPost.java
  src/main/java/com/threego/algo/coding/query/controller/CodingProblemQueryController.java
  src/main/java/com/threego/algo/coding/query/dto/CodingPostSearchConditionDTO.java
  src/main/java/com/threego/algo/coding/query/dto/CodingProblemDetailDTO.java
  src/main/resources/com/threego/algo/coding/query/dao/CodingProblemMapper.xml
  src/test/java/com/threego/algo/AlgoApplicationTests.java
  src/test/java/com/threego/algo/coding/command/application/service/CodingPostCommandServiceImplTest.java
Labels: 코딩 풀이

#45 [Feat] #25 - 신고 당한 게시물/댓글 내용 조회
  src/main/java/com/threego/algo/report/query/controller/AdminReportQueryController.java
  src/main/java/com/threego/algo/report/query/dao/ReportMapper.java
  src/main/java/com/threego/algo/report/query/dto/ReportContentResponseDTO.java
  src/main/java/com/threego/algo/report/query/service/AdminReportQueryService.java
  src/main/java/com/threego/algo/report/query/service/AdminReportQueryServiceImpl.java
  src/main/resources/com/threego/algo/report/query/dao/ReportMapper.xml
Labels: 신고

#49 [Feat] #48 알고리즘 학습 게시물 추천 테스트 코드 작성 및 CodingPostImageRepository 중복 주입 삭제
  src/main/java/com/threego/algo/coding/command/application/service/CodingPostCommandServiceImpl.java
  src/test/java/com/threego/algo/algorithm/query/service/AlgoQueryServiceTest.java
Labels: Hotfix, 알고리즘 학습
